### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Eikichi** [CLLKazan/UIMA-Ext#5]
Я пытаюсь выполнить compile-dictionary.sh, но выходит эта ошибка, а точнее так:
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/JCommander
        at ru.ksu.niimm.cll.uima.morph.opencorpora.resource.XmlDictionaryParserLauncher.main(XmlDictionaryParserLauncher.java:45)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.JCommander
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

Я загуглил эту проблему, там предлагают проследить за изменениями classpath, но я добавил нужные папки в переменные среды, может даже немного лишнего - не помогло. Это я глупый или есть какая-то ошибка?

**Comment by rgareev** [comment]
Здравствуйте!
Вы работает с веткой master? Или с тэгом russir2014-paper ?
В первом случае, скорее всего, из-за последующих изменений в PosTaggingLab пропала зависимость от jcommander. Вы можете добавить её в classpath вручную - http://search.maven.org/#artifactdetails%7Ccom.beust%7Cjcommander%7C1.32%7Cjar.

**Comment by Eikichi** [comment]
Спасибо за ответ.
Да, работал с веткой master. Попробовал с russir2014-paper, но при попытке построить проект выводит следующее:
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building UIMA.Ext.Morph.PosTaggingLab 0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-morph-treetagger/0.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata ru.ksu.niimm.cll.uima:uima-ext-morph-treetagger:0.3-SNAPSHOT/maven-metadata.xml from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-morph-treetagger/0.3-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
[WARNING] Failure to transfer ru.ksu.niimm.cll.uima:uima-ext-morph-treetagger:0.3-SNAPSHOT/maven-metadata.xml from http://cll.niimm.ksu.ru:8080/artifactory/repo was cached in the local repository, resolution will not be reattempted until the update interval of cll.artifactory has elapsed or updates are forced. Original error: Could not transfer metadata ru.ksu.niimm.cll.uima:uima-ext-morph-treetagger:0.3-SNAPSHOT/maven-metadata.xml from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-morph-treetagger/0.3-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
Downloading: http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-morph-treetagger/0.3-SNAPSHOT/uima-ext-morph-treetagger-0.3-SNAPSHOT.pom
Downloading: http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-morph-opencorpora/0.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata ru.ksu.niimm.cll.uima:uima-morph-opencorpora:0.3-SNAPSHOT/maven-metadata.xml from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-morph-opencorpora/0.3-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
[WARNING] Failure to transfer ru.ksu.niimm.cll.uima:uima-morph-opencorpora:0.3-SNAPSHOT/maven-metadata.xml from http://cll.niimm.ksu.ru:8080/artifactory/repo was cached in the local repository, resolution will not be reattempted until the update interval of cll.artifactory has elapsed or updates are forced. Original error: Could not transfer metadata ru.ksu.niimm.cll.uima:uima-morph-opencorpora:0.3-SNAPSHOT/maven-metadata.xml from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-morph-opencorpora/0.3-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
Downloading: http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-morph-opencorpora/0.3-SNAPSHOT/uima-morph-opencorpora-0.3-SNAPSHOT.pom
Downloading: http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-pos-tagger-opennlp/0.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata ru.ksu.niimm.cll.uima:uima-ext-pos-tagger-opennlp:0.3-SNAPSHOT/maven-metadata.xml from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-pos-tagger-opennlp/0.3-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
[WARNING] Failure to transfer ru.ksu.niimm.cll.uima:uima-ext-pos-tagger-opennlp:0.3-SNAPSHOT/maven-metadata.xml from http://cll.niimm.ksu.ru:8080/artifactory/repo was cached in the local repository, resolution will not be reattempted until the update interval of cll.artifactory has elapsed or updates are forced. Original error: Could not transfer metadata ru.ksu.niimm.cll.uima:uima-ext-pos-tagger-opennlp:0.3-SNAPSHOT/maven-metadata.xml from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-pos-tagger-opennlp/0.3-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
Downloading: http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-pos-tagger-opennlp/0.3-SNAPSHOT/uima-ext-pos-tagger-opennlp-0.3-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.008s
[INFO] Finished at: Fri Feb 13 22:54:28 MSK 2015
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project morph-pos-tagging-lab: Could not resolve dependencies for project ru.ksu.niimm.cll.uima:morph-pos-tagging-lab:jar:0.3-SNAPSHOT: Failed to collect dependencies for [ru.ksu.niimm.cll.uima:uima-ext-morph-treetagger:jar:0.3-SNAPSHOT (compile), ru.ksu.niimm.cll.uima:uima-morph-opencorpora:jar:0.3-SNAPSHOT (compile), ru.ksu.niimm.cll.uima:uima-ext-pos-tagger-opennlp:jar:0.3-SNAPSHOT (compile), de.tudarmstadt.ukp.dkpro.lab:de.tudarmstadt.ukp.dkpro.lab.uima.engine.cpe:jar:0.9.1 (compile), org.apache.uima:uimaj-core:jar:2.4.2 (compile), org.uimafit:uimafit:jar:1.4.0 (compile), com.google.guava:guava:jar:14.0.1 (compile), org.apache.commons:commons-lang3:jar:3.1 (compile), commons-dbcp:commons-dbcp:jar:1.4 (compile), org.springframework:spring-jdbc:jar:3.2.1.RELEASE (compile), org.hsqldb:hsqldb:jar:2.3.2 (compile?), ch.qos.logback:logback-classic:jar:1.0.9 (compile), junit:junit:jar:4.11 (test)]: Failed to read artifact descriptor for ru.ksu.niimm.cll.uima:uima-ext-morph-treetagger:jar:0.3-SNAPSHOT: Could not transfer artifact ru.ksu.niimm.cll.uima:uima-ext-morph-treetagger:pom:0.3-SNAPSHOT from/to cll.artifactory (http://cll.niimm.ksu.ru:8080/artifactory/repo): Access denied to http://cll.niimm.ksu.ru:8080/artifactory/repo/ru/ksu/niimm/cll/uima/uima-ext-morph-treetagger/0.3-SNAPSHOT/uima-ext-morph-treetagger-0.3-SNAPSHOT.pom. Error code 401, Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Пробовал и так и эдак. Пока вернулся к master, там хоть я вроде могу что-то исправить. Попробовал добавить JCommander, хотя он там в зависимостях присутствует. Безрезультатно. Может дело в том, что в скрипте compile-dictionary.sh переписывается classpath?

**Comment by rgareev** [comment]
Насчет ошибки при билде исходников, протэгированных russir-2014.  http://cll.niimm.ksu.ru:8080/artifactory/repo . У нас после этого поменялся URL немного. В master же прописал правильный.
Я проверил сборку assembly-архива (в master) MorphPosTaggingLab: compile-dictionary.sh запускает java-приложение у которого есть в classpath jcommander.
Это видно из dependency:tree maven'а (можно запустить mvn dependency:tree в MorphPosTaggingLab):

```
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ morph-pos-tagging-lab ---
[INFO] ru.ksu.niimm.cll.uima:morph-pos-tagging-lab:jar:0.4-SNAPSHOT
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-eval:jar:0.4-SNAPSHOT:compile
[INFO] |  +- ru.ksu.niimm.cll.uima:uima-ext-commons:jar:0.4-SNAPSHOT:compile
[INFO] |  |  \- org.apache.uima:uimaj-cpe:jar:2.4.2:compile
[INFO] |  |     +- org.apache.uima:uimaj-adapter-vinci:jar:2.4.2:compile
[INFO] |  |     \- org.apache.uima:jVinci:jar:2.4.2:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- org.springframework:spring-context:jar:3.2.1.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:3.2.1.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:3.2.1.RELEASE:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.2:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-freq-baseline:jar:0.4-SNAPSHOT:compile
[INFO] |  +- ru.ksu.niimm.cll.uima:uima-ext-postagger-api:jar:0.4-SNAPSHOT:compile
[INFO] |  |  \- ru.ksu.niimm.cll.uima:uima-ext-tokenizer-api:jar:0.4-SNAPSHOT:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-dict-baseline:jar:0.4-SNAPSHOT:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-treetagger:jar:0.4-SNAPSHOT:compile
[INFO] |  +- org.annolab.tt4j:org.annolab.tt4j:jar:1.1.1:compile
[INFO] |  +- ru.ksu.niimm.cll.uima:uima-ext-sentence-splitter-api:jar:0.4-SNAPSHOT:compile
[INFO] |  \- com.beust:jcommander:jar:1.32:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-hunpos:jar:0.4-SNAPSHOT:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-stanford:jar:0.4-SNAPSHOT:compile
[INFO] |  \- edu.stanford.nlp:stanford-postagger:jar:3.3.0:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-pos-tagger-opennlp:jar:0.4-SNAPSHOT:compile
[INFO] |  +- org.apache.opennlp:opennlp-tools:jar:1.5.3:compile
[INFO] |  |  +- org.apache.opennlp:opennlp-maxent:jar:3.0.3:compile
[INFO] |  |  \- net.sf.jwordnet:jwnl:jar:1.3.3:compile
[INFO] |  \- org.cleartk:cleartk-ml:jar:1.3.0:compile
[INFO] |     \- org.cleartk:cleartk-util:jar:0.9.2:compile
[INFO] |        +- args4j:args4j:jar:2.0.16:compile
[INFO] |        \- com.carrotsearch:hppc:jar:0.4.1:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-tcrf:jar:0.4-SNAPSHOT:compile
[INFO] |  \- ru.ksu.niimm.cll.uima:uima-ext-ml-crfsuite:jar:0.4-SNAPSHOT:compile
[INFO] |     \- ru.kfu.itis.issst.crfsuite4j:crfsuite4j:jar:0.2-SNAPSHOT:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-morph-dictionary-opencorpora:jar:0.4-SNAPSHOT:compile
[INFO] |  \- ru.ksu.niimm.cll.uima:uima-ext-morph-dictionary-api:jar:0.4-SNAPSHOT:compile
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-postagger-util-rnc:jar:0.4-SNAPSHOT:runtime
[INFO] +- ru.ksu.niimm.cll.uima:uima-ext-tokenizer-simple:jar:0.4-SNAPSHOT:runtime
[INFO] +- de.tudarmstadt.ukp.dkpro.lab:de.tudarmstadt.ukp.dkpro.lab.uima.engine.cpe:jar:0.9.1:compile
[INFO] |  \- de.tudarmstadt.ukp.dkpro.lab:de.tudarmstadt.ukp.dkpro.lab.uima:jar:0.9.1:compile
[INFO] |     \- de.tudarmstadt.ukp.dkpro.lab:de.tudarmstadt.ukp.dkpro.lab.core:jar:0.9.1:compile
[INFO] |        +- org.apache.commons:commons-math:jar:2.1:compile
[INFO] |        +- org.safehaus.jug:jug:jar:asl:2.0.0:compile
[INFO] |        +- org.json:json:jar:20090211:compile
[INFO] |        +- jfree:jfreechart:jar:1.0.13:compile
[INFO] |        |  \- jfree:jcommon:jar:1.0.16:compile
[INFO] |        +- net.sf.opencsv:opencsv:jar:2.0:compile
[INFO] |        +- org.apache.avalon.framework:avalon-framework-impl:jar:4.3.1:compile
[INFO] |        |  \- org.apache.avalon.framework:avalon-framework-api:jar:4.3.1:compile
[INFO] |        +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |        \- org.apache.ant:ant:jar:1.8.3:compile
[INFO] |           \- org.apache.ant:ant-launcher:jar:1.8.3:compile
[INFO] +- org.apache.uima:uimaj-core:jar:2.4.2:compile
[INFO] +- org.uimafit:uimafit:jar:1.4.0:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.6:compile (version managed from 2.4)
[INFO] |  +- org.apache.uima:uimaj-tools:jar:2.4.0:compile
[INFO] |  |  \- org.apache.uima:uimaj-document-annotation:jar:2.4.0:compile
[INFO] |  \- org.springframework:spring-core:jar:3.2.1.RELEASE:compile
[INFO] +- com.google.guava:guava:jar:14.0.1:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.1:compile
[INFO] +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  \- commons-pool:commons-pool:jar:1.5.4:compile
[INFO] +- org.springframework:spring-jdbc:jar:3.2.1.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:3.2.1.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  \- org.springframework:spring-beans:jar:3.2.1.RELEASE:compile
[INFO] +- org.hsqldb:hsqldb:jar:2.3.2:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.0.9:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.0.9:compile
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```
То есть jcommander является транзитивной зависимостью morph-pos-tagging-lab. На будущее я сейчас сделаю коммит, где эта зависимость будет прямой.

Вам бы я рекомендовал, при работе с master, откатить свои изменения, сделать git pull и попробовать ещё раз.

**Comment by Eikichi** [comment]
Теперь все получилось. Спасибо!
